package:
  name: bioconductor-rcas
  version: 0.1

source:
  path: /home/dilmurat/workspace/RCAS/rpackage/RCAS/
  git_rev:
build:
  number: 1

requirements:
  build:
    - r
    - bioconductor-biomart
    - bioconductor-org.hs.eg.db
    - bioconductor-org.mm.eg.db
    - bioconductor-org.ce.eg.db
    - bioconductor-org.dm.eg.db
    - bioconductor-topgo
    - bioconductor-genomicfeatures
    - bioconductor-genomation
    - bioconductor-rtracklayer
    - bioconductor-annotationdbi
    - bioconductor-genomicranges
    - bioconductor-bsgenome.hsapiens.ucsc.hg19
    - bioconductor-bsgenome.mmusculus.ucsc.mm9
    - bioconductor-bsgenome.celegans.ucsc.ce6
    - bioconductor-bsgenome.dmelanogaster.ucsc.dm3
    - bioconductor-genomeinfodb
    - bioconductor-biostrings
    - bioconductor-motifrg
    - r-rmarkdown
    - r-plotly
    - r-dt
    - r-data.table
    - pandoc >=1.16.0.2
  run:
    - r
    - bioconductor-biomart
    - bioconductor-org.hs.eg.db
    - bioconductor-org.mm.eg.db
    - bioconductor-org.ce.eg.db
    - bioconductor-org.dm.eg.db
    - bioconductor-topgo
    - bioconductor-genomicfeatures
    - bioconductor-genomation
    - bioconductor-rtracklayer
    - bioconductor-annotationdbi
    - bioconductor-genomicranges
    - bioconductor-bsgenome.hsapiens.ucsc.hg19
    - bioconductor-bsgenome.mmusculus.ucsc.mm9
    - bioconductor-bsgenome.celegans.ucsc.ce6
    - bioconductor-bsgenome.dmelanogaster.ucsc.dm3
    - bioconductor-genomeinfodb
    - bioconductor-biostrings
    - bioconductor-motifrg
    - r-rmarkdown
    - r-plotly
    - r-dt
    - r-data.table
    - pandoc >=1.16.0.2
test:
  commands:
    - $R -e "library('RCAS')"

about:
  home: https://github.com/BIMSBbioinfo/RCAS/tree/rcas_R/rpackage/RCAS
  license: Artistic-2.0Artistic-2.0
  summary: 'RNA Centric Annotation System (RCAS) is an automated system
  that provides dynamic annotations for custom input files
  that contain transcriptomic targe regions.'
