package:
  name: pandoc
  version: 1.17.0.2

source:
  fn: 1.17.0.2.tar.gz  [linux]
  url: https://github.com/jgm/pandoc/archive/1.17.0.2.tar.gz  # [linux]
  md5sum: d288c4b028cf9b0b29400c384f4d4baf

test:
  commands:
    - pandoc --help

requirements:           # [linux]
  build:                # [linux]
    - gmp 4.*           # [linux]
    - libffi            # [linux]
    - zlib              # [linux]
  run:                  # [linux]
    - gmp 4.*           # [linux]
    - libffi            # [linux]
    - zlib              # [linux]

build:  # [linux]
  number: 1 # [linux]

about:
  home: http://johnmacfarlane.net/pandoc/
  license: GPL
  summary: Universal markup converter
